name: nigtlytool linux

on:
  push:
    branches: [ !main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_hash: ${{ steps.build.outputs.commit_hash }}

    steps:
      - uses: actions/checkout@v2

      - name: set up
        run: |
          sudo apt update
          sudo apt install g++

      - name: build
        id: build
        run: |
          g++ skyrmng.cpp -o skyrmng
          mkdir -p ~/artifacts
          cp skyrmng ~/artifacts
          echo ::set-output name=commit_tag::$(git describe --abbrev=0 --tags)
          echo ::set-output name=commit_hash::$(git log --format=%h -1)
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: ubuntu
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on Windows
        shell: bash
        run: g++ skyrmng.cpp -o skyrmng.exe
      - name: "Publish build to GH Actions"
        uses: actions/upload-artifact@v2
        with:
          path: skyrmng.exe
          name: "windows"
  publish_build:
    runs-on: ubuntu-latest
    name: Publish build to skymz4/builds
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: [build, windows]
    env:
      COMMIT_TAG: ${{ needs.build.outputs.commit_tag }}
      COMMIT_HASH: ${{ needs.build.outputs.commit_hash }}
    outputs:
      current_date: ${{ steps.commit.outputs.current_date }}
    steps:
      - name: Download artifacts ubuntu
        uses: actions/download-artifact@v2
        with:
          name: ubuntu
          path: ubuntu

      - name: Download artifacts windows
        uses: actions/download-artifact@v2
        with:
          name: windows
          path: windows

      - name: Commit and push to skymz4/builds
        id: commit
        run: |
          CURRENT_DATE=$(date +"%Y%m%d-%H%M%S")
          echo ::set-output name=current_date::$CURRENT_DATE
          git config --global user.email "tobid7@outlook.de"
          git config --global user.name "Tobi-D7"
          git clone --depth 1 https://${{ secrets.TOKEN }}@github.com/skymz4/builds.git
          cd builds
          cp ${{ github.workspace }}/windows/* .
          cp ${{ github.workspace }}/ubuntu/* .
          git stage ./*.exe
          git stage skyrmng
          git commit -m "skyrmng | $COMMIT_HASH"
          git tag v$CURRENT_DATE
          git push origin master v$CURRENT_DATE
